Weather App Functionality
OA7/JS-Weather-App pull request #1
Opened 2020-09-12 04:14 UTC by OA7

- When you load the app, by default it shows the weather for your specific location if you have location services turned on.
- It does not show the weather forecast for the next 3 days as when you search for a city, it shows some dummy text.
- You can search for any city and it returns the weather for that day and a forecast for the next 3 days.
- The app uses [Skycons](https://darkskyapp.github.io/skycons/) for the animated icons that show up based on the weather details. 

**_Presently no live demo available, plan to add one after the project gets approved._**

2020-09-12 10:39 UTC, uche-inyama requested changes
## Changes required.

Hi @OA7, :wave: 

Your project works well :+1: 

However, there is an update you need to make in your codebase.

- [ ] You have commented lines of code in skycon.js file, remove them.

When you are done with the update, submit another form for a code review.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2020-09-12 11:36 UTC, OA7 commented
`skycons.js` is an imported library, the code in it is not mine, I use it to show weather animations in my app.

2020-09-12 14:28 UTC, uryelah requested changes
Hi **Osong Agberndifor**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with your project! It's very nice and one can see you are very comfortable working with Javascript and the DOM.

There are some minor issues, scripts missing, the README instructions, and console.logs, that you'll have to fix before getting it approved but it will be pretty trivial compared to what you already have.

About the animation library, you are using, in the next projects, I'd try to opt for using libraries with a CDN or installed via npm || yarn instead.

Rock on! 🎸 👨‍🎤 

# Required Changes 🏗️ 🐛 💡

(Check the comments below for the required fixes)

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-09-12 14:28 UTC, uryelah commented on README.md
> +2. Open with your favorite text editor and run with a live server.
- [ ] How exackly the user can run the live server? Be specific with the files and commands needed.
Add the `start` command to the scripts and then you can instruct them on using `npm run start`.

2020-09-12 14:28 UTC, uryelah commented on dist/styles/styles.css
> +#description {
- [ ] Please don't use ids for stylng purposes, they can cause bugs as your app styles grow in complexity as their priority is too high. Just add a class of the same name to the element.

2020-09-12 14:28 UTC, uryelah commented on src/forecast.js
> +      console.log(error);
- [ ] Instead of using a console.log for the error handle it by returning it/use callback to display it in the DOM.

2020-09-12 14:28 UTC, uryelah commented on src/index.js
> +const apiKey = 'a6cd07c7544e20ce06689d0d815f4222';
- [ ] [OPTIONAL] After the project is merged considers storing the key as an enviromental variable instead of exposing it on your repo. You can even use webpack for that if you search the documentation.

2020-09-12 14:28 UTC, uryelah commented on src/index.js
> +      console.log(error);
- [ ] Try to handle the error without the logging it to the console alone.

2020-09-12 14:28 UTC, uryelah commented on src/index.js
> +  const days1 = list[0];
[ ] [OPTIONAL] A lot of the code in this function is repeated 3 times, why don't you try using a loop to avoid repeating code?

2020-09-12 14:28 UTC, uryelah commented on src/user.js
> +const userLoad = () => {
- [ ] [OPTIONAL] This function is doing a lot of things at the same time, can you make it more modular? The code inside the .then could come from anothe function for example.

2020-09-12 14:28 UTC, uryelah commented on webpack.config.js
> +  },
- [ ] When you add the `start` script make sure to add the devserver configuration here.

2020-09-12 14:28 UTC, uryelah commented on README.md
> +2. Open with your favorite text editor and run with a live server.
- [ ] The scripts at your package.json should look similar to:
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```
Make sure all the scripts are working after adding them and to install any needed dependency.

2020-09-12 14:30 UTC, uryelah commented on webpack.config.js
> +  },
This link has some details on how to implement that: https://webpack.js.org/guides/development/

2020-09-12 15:08 UTC, OA7 commented on README.md
> +2. Open with your favorite text editor and run with a live server.
I understand what you mean, but the way I configured my webpack, a web-dev-server is not needed to run the application, right-clicking on the index.html file and choosing the "Open with liver server works fine".

2020-09-12 15:45 UTC, uryelah commented on README.md
> +2. Open with your favorite text editor and run with a live server.
Perfect, just make sure to include that info in the readme.

2020-09-13 10:33 UTC, bellom approved these changes
## Hi @OA7  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-09-13 19:56 UTC, merged